# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/python_dash_template/',
                'doc_host': 'https://dataforgoodfr.github.io',
                'git_url': 'https://github.com/dataforgoodfr/https://github.com/dataforgoodfr/python-dash-template/',
                'lib_path': 'python_dash_template'},
  'syms': {'python_dash_template.core': {}}}
